import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { app } from '../src/app.js';
import { generateRouteMap, RouteInfo } from '../src/utils/routeMap.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const DOCS_PATH = path.resolve(__dirname, '../docs/api-routes.md');

export function generateMarkdown(routes: RouteInfo[]): string {
  let md = '# API Route Map\n\n';
  md += 'This file is automatically generated from the Express router stack. Do not edit manually.\n\n';
  md += '| Method | Path |\n';
  md += '|---|---|\n';

  // Sort routes logically: by path, then method
  routes.sort((a, b) => {
    if (a.path !== b.path) {
      return a.path.localeCompare(b.path);
    }
    return a.method.localeCompare(b.method);
  });

  for (const route of routes) {
    md += `| \`${route.method}\` | \`${route.path}\` |\n`;
  }

  return md;
}

export function main() {
  try {
    const routes = generateRouteMap(app);
    const md = generateMarkdown(routes);
    
    // Ensure docs directory exists
    const docsDir = path.dirname(DOCS_PATH);
    if (!fs.existsSync(docsDir)) {
      fs.mkdirSync(docsDir, { recursive: true });
    }

    fs.writeFileSync(DOCS_PATH, md);
    console.log(`✅ Generated API route map at ${DOCS_PATH}`);
  } catch (err) {
    console.error('❌ Failed to generate API route map:', err);
    process.exit(1);
  }
}

// Run if called directly
if (process.argv[1] === __filename) {
  main();
}
